version: '3.9'

services:
  # Database
  db:
    #image: mysql
    build: ./bd/.
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_projeto
    ports:
      - "3308:3306"
  # Phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
 # Node
  node:
    build: .
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: /bin/sh -c "npm install"
    
networks:
  wpsite:
volumes:
  db_data: