version: '3.9'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:8080'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
 # Node
  node:
    build: .
    ports:
      - "8081:8081"
    restart: always
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    command: /bin/sh -c "npm install"
    
networks:
  wpsite:
volumes:
  db_data: